### ISSUE TITLE
Bug #Logic Error

### ISSUE THREAD

**Issue by MSubhajitIND** [replyre/Tic_Tac_Toe-React#1]
I have not reviewed your code but while testing found this bug.

![err1](https://github.com/replyre/Tic_Tac_Toe-React/assets/75659257/40aa0c32-78f3-4f66-97e0-7ee130ea7fca)
![err2](https://github.com/replyre/Tic_Tac_Toe-React/assets/75659257/1f8fdf35-ff2f-46cb-a88d-87b7a359b28b)

**Comment by replyre** [comment]
okay @MSubhajitIND , thanks for letting me know.I will see through this issue or would you like to work on this ?

**Comment by MSubhajitIND** [comment]
Thanks For offering,

I am busy coming 3-5 months for my examination. I just randomly visiting profiles and found this bug ... so I informed you. 

If you are unable to solve you can assign me I will work at the time of Christmas.

**Comment by replyre** [comment]
Okay, no issues, I will look into it myself, again thanks for letting me know.
